### ISSUE TITLE
make compiler and runner redshift-dumb

### ISSUE THREAD

**Issue by drewbanin** [analyst-collective/dbt#127]
to support BQ

**Comment by jthandy** [comment]
@drewbanin is this still a thing once @cmcarthur's snowflake changes are done?

**Comment by drewbanin** [comment]
I defer to @cmcarthur here. I suspect there's more work to do on this front though

**Comment by cmcarthur** [comment]
There is more work to be done here, but I don't think this issue scopes any useful work. There are still some shared templates for incremental models because Postgres, Redshift, and Snowflake share a SQL dialect. These will need to be updated when we support a SQL dialect either (a) without DDL support (Bigquery) or (b) with slightly different syntax (MySQL). We can resolve this when we add support for one of those adapters.

**Comment by jthandy** [comment]
👍 closing.
