### ISSUE TITLE
Error executing ... relation ... does not exist

### ISSUE THREAD

**Issue by dannybrown2** [analyst-collective/dbt#133]
It appears the dependency graph is not queing the correct items. It is telling me that a relation does not exist but when i manually run those relations first I don't receive the error.
[interactions_error.txt](https://github.com/analyst-collective/dbt/files/443599/interactions_error.txt)

**Comment by drewbanin** [comment]
@dannybrown2 sorry for letting this slide! Do you think this happened because you ran `dbt run --model interactions` w/o the `email_interactions` table already existing?

The `--model` flag runs all models which depend on the specified model, but it doesn't go "up" the graph and create the predecessors which the specified model depends on.

Duncan had a good idea, `--model` should also be able to create predecessors which don't already exist. Do you think this would alleviate you're issue?

**Comment by dannybrown2** [comment]
@drewbanin I think that is what happened to me. Duncan explained it a bit and I did some testing. Running dbt run loaded it correctly. Since the pre_conversion_interactions.sql depends on both other_interactions.sql and email_interactions.sql going up the chain didn't quite solve it either as it required me to run both.

In short I think that would be a great idea if the --model created predecessors.

**Comment by drewbanin** [comment]
Great, totally reasonable. Going to create an issue for `--model` predecessors. Closing!
