### ISSUE TITLE
--models should also run predecessors 

### ISSUE THREAD

**Issue by drewbanin** [analyst-collective/dbt#134]
`dbt run --models [model1] [model2]...` should run predecessors if the required tables don't exist. 

If the preceding tables do exist, should they be recalculated? Should there be other CLI options to manage what gets run? Like `--only-up` or `--only-down`? Keen to hear thoughts from @jthandy, @dannybrown2 and @duncancfraser

**Comment by jthandy** [comment]
@drewbanin this is something I've thought a lot about, and mentioned to you in passing but we've never really gone into detail about it. Here are the things that I believe to be true on this topic:

- the `--models` CLI option is primarily for development, to make building the model that you're currently working on take far less time. In my 60+ model uservoice repository, this option saves me a TON of time. In my view, this flag shouldn't change from its current functionality.

- selecting nodes from the graph to be included in a given `dbt run` is a deep area of functionality within a production context. there is a lot of complexity here that we will eventually need to handle in order to provide users with options to implement all of the various schemes that they might want. scheduling, cascading schedules for dependencies (or not), running only certain parts of a graph (dependencies or predecessors or all models that have certain criteria like incremental materialization), etc. there's a lot to do here. I don't have strong feelings here yet, *except* that we shouldn't attempt to shoehorn all of this functionality into the `--models` flag referred to above. I want that to stay simple, for the stated use case.

I think that the latter of these things is a big topic that we should think a lot more about before attempting to build anything. I think it's very worthy of its own feature issue that we can manage the dialog on, but the context for that issue should look more like "flexibly select nodes from the graph to be run". 

@drewbanin comments?

**Comment by drewbanin** [comment]
@jthandy agreed, there are super complex ways to interact with the dependency graph... we should definitely put more thought into this before building some sort of [graph query language DSL](https://neo4j.com/developer/cypher-query-language/).

Maybe the right thing to do in this scenario (for now) is to throw a more helpful error message.
