### ISSUE TITLE
"incremental" deploy

### ISSUE THREAD

**Issue by drewbanin** [analyst-collective/dbt#48]
only update views/tables which have changed
for developmental debugging, not for production

**Comment by jthandy** [comment]
Rather than detecting changes, it may be easier to just have a --models flag that you can send a list to and it will just deploy those models and their dependencies.

This would be very useful in another situation as well. With a client, I'm building a bunch of models that are views and stacking them on top of one another. Then, in a final model, I'm taking the results of the final view and storing them to disk. This dramatically speeds up analytical query performance. I would ideally like to be able to say `dbt run --model transactions` or something similar to only build this final one. I could imagine wanting to do this in production on an ongoing basis so as to avoid tearing down all of the underlying views every hour in a production environment.

**Comment by drewbanin** [comment]
deployed!
